apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
    role: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
      role: controller
  template:
    metadata:
      labels:
        app: controller
        role: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: emirozbir/redis-cont:0.0.3
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "python3 /opt/update_svc.py" ]

          env:
            - name: REDIS_CLUSTER_NAMESPACE
              value: "default"
            - name: MASTER_NAME
              value: "redis-ha"
            - name: SENTINEL_SERVICE_HOST
              value: "sentinel-svc-redis-ha-redis-sentinel"
            - name: PYTHONUNBUFFERED
              value: "1"
